### ISSUE TITLE
Can install via CocoaPods

### ISSUE THREAD

**Issue by danialepacoMandao** [paulsumit1993/ContactsSuggestionTextField#1]

**Comment by paulsumit1993** [comment]
Hey @danialepacoMandao 
I'm not sure what you mean by the title, i'm assuming that you are facing problems installing the library via cocoapods. In that case, you can follow the [Installation](https://github.com/paulsumit1993/ContactsSuggestionTextField#installation) guide.

Lets me know if that helps.
